trim/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin

from trim_app.views import MainView, TaskListView, AddUserView, UserLoginView, UserLogoutView,\
    TaskCreate, TaskDetailsView, UpdateTask, DeleteTask, TeamMemberView, AddTeamMemberView, \
    TeamView, UpdateApproval, UpdatePerson


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainView.as_view(), name="main"),
    url(r'^task_list$', TaskListView.as_view(), name="task-list"),
    url(r'^add_user$', AddUserView.as_view(), name="add-user"),
    url(r'^login$', UserLoginView.as_view(), name="login"),
    url(r'^logout$', UserLogoutView.as_view(), name="logout"),
    url(r'^create_task$', TaskCreate.as_view(), name="create-task"),
    url(r'^task_details/(?P<task_id>(\d)+)', TaskDetailsView.as_view(), name="task-details"),
    url(r'^update_task/(?P<pk>(\d)+)$', UpdateTask.as_view(), name="update-task"),
    url(r'^delete_task/(?P<pk>(\d)+)$', DeleteTask.as_view(), name="delete-task"),
    url(r'^team_member/(?P<teammember_id>(\d)+)', TeamMemberView.as_view(), name="team-member"),
    url(r'^add_team_member$', AddTeamMemberView.as_view(), name="add-team-member"),
    url(r'^team/(?P<id>(\d)+)', TeamView.as_view(), name="team"),
    url(r'^update_approval/(?P<pk>(\d)+)$', UpdateApproval.as_view(), name="update-approval"),
    url(r'^update_person/(?P<pk>(\d)+)$', UpdatePerson.as_view(), name="update-person"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trim_app/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class TeamMember(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    position = models.CharField(max_length=32)
    team = models.ForeignKey(Team, related_name='team_member', on_delete=models.CASCADE)

    @property
    def name(self):
        first_name = self.user.first_name
        last_name = self.user.last_name
        return "{} {}".format(first_name, last_name)

    def __str__(self):
        return self.name


MONTHS= (
    (1, 'Jan'),
    (2, 'Feb'),
    (3, 'Mar'),
    (4, 'Apr'),
    (5, 'May'),
    (6, 'Jun'),
    (7, 'Jul'),
    (8, 'Aug'),
    (9, 'Sep'),
    (10, 'Oct'),
    (11, 'Nov'),
    (12, 'Dec'),
)


DAYS = (
    (1, 'middle month'),
    (2, 'D-5'),
    (3, 'D-4'),
    (4, 'D-3'),
    (5, 'D-2'),
    (6, 'D-1'),
    (7, 'D1'),
    (8, 'D2'),
    (9, 'D3'),
    (10, 'D4'),
    (11, 'D5'),
)


PRIORITIES = (
    (1, 'high'),
    (2, 'middle'),
    (3, 'low'),
)


FREQUENCIES = (
    (1, 'monthly'),
    (2, 'quarterly'),
    (3, 'yearly'),
    (4, 'ad hoc'),
)


STATUSES = (
    (1, 'not started'),
    (2, 'in progress'),
    (3, 'completed'),
)


class Task(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(default=None, blank=True)
    priority = models.IntegerField(choices=PRIORITIES)
    start_date = models.DateTimeField(default=datetime.now, blank=True)
    month = models.IntegerField(choices=MONTHS)
    due = models.IntegerField(choices=DAYS)
    frequency = models.IntegerField(choices=FREQUENCIES)
    department = models.ForeignKey(Team, related_name='task_team', on_delete=models.CASCADE)
    responsible = models.ForeignKey(TeamMember, related_name='task_person', on_delete=models.CASCADE)
    backup = models.ForeignKey(TeamMember, related_name='task_backup', on_delete=models.CASCADE, blank=True)
    approver = models.ForeignKey(TeamMember, related_name='task_approver', on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES)
    end_date = models.DateTimeField(default=None, blank=True, null=True)
    approval = models.BooleanField(default=False)
    approval_date = models.DateTimeField(default=None, blank=True, null=True)


    def __str__(self):
        return self.name

trim_app/forms.py
from django import forms
from .models import Team, TeamMember, Task, PRIORITIES, DAYS, STATUSES, FREQUENCIES
from django.core.validators import validate_email, URLValidator


DAYS = (
    (1, 'middle month'),
    (2, 'D-5'),
    (3, 'D-4'),
    (4, 'D-3'),
    (5, 'D-2'),
    (6, 'D-1'),
    (7, 'D1'),
    (8, 'D2'),
    (9, 'D3'),
    (10, 'D4'),
    (11, 'D5'),
)


PRIORITIES = (
    (1, 'high'),
    (2, 'middle'),
    (3, 'low'),
)


FREQUENCIES = (
    (1, 'monthly'),
    (2, 'quarterly'),
    (3, 'yearly'),
    (4, 'ad hoc'),
)


STATUSES = (
    (1, 'not started'),
    (2, 'in progress'),
    (3, 'completed'),
)


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', strip=True)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class AddUserForm(forms.Form):
    login = forms.CharField(label='Login', strip=True)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password_check = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    first_name = forms.CharField(label='First name', strip=True)
    last_name = forms.CharField(label='Last name', strip=True)
    email = forms.EmailField(label="Email")


class TaskForm(forms.Form):
    name = forms.CharField(label='Task')
    description = forms.CharField(label='Description')
    priority = forms.ChoiceField(label='Priority', choices=PRIORITIES)
    start_date = forms.DateTimeField(label='Start date')
    due = forms.ChoiceField(label='Due', choices=DAYS)
    frequency = forms.ChoiceField(label='Frequency', choices=FREQUENCIES)
    department = forms.CharField(label='Department')
    responsible = forms.CharField(label='Responsible')
    backup = forms.CharField(label='Backup')
    approver = forms.CharField(label='Approver')
    status = forms.ChoiceField(label='Status', choices=STATUSES)
    end_date = forms.DateTimeField(label='End date')


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'


class EditTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['status', 'end_date']


class Search(forms.Form):
    position = forms.CharField(label='Position', max_length=64)
    # user = forms.CharField(label='User', max_length=64)

trim_app/views.py
from django import forms
from django.contrib import admin, messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse, reverse_lazy

from .models import Team, TeamMember, Task
from .forms import AddUserForm, LoginForm


class MainView(View):
    def get(self, request):
        task_list = Task.objects.filter(end_date=None).order_by('due')
        teammembers_list = TeamMember.objects.all()
        teams = Team.objects.all()
        ctx= {
            'task_list': task_list,
            'teammembers_list': teammembers_list,
            'teams': teams
        }
        if not request.user.is_authenticated:
            return redirect('login')
        return render(
            request,
            template_name='main.html',
            context=ctx
        )


class TaskListView(View):
    def get(self, request):
        task_list = Task.objects.all().order_by('due')
        ctx= {
            'task_list': task_list,
        }
        if not request.user.is_authenticated:
            return redirect('login')
        return render(
            request,
            template_name='task_list.html',
            context=ctx
        )


class AddUserView(View):
    def get(self, request):
        form = AddUserForm()
        ctx = {
            'form': form
        }
        return render(
            request,
            template_name='add_user.html',
            context=ctx
        )

    def post(self, request):
        form = AddUserForm(request.POST)
        if form.is_valid():
            login = form.cleaned_data['login']
            if User.objects.filter(username=login).exists():
                form.add_error('login', "Taki login jest już zajęty.")
            password = form.cleaned_data['password']
            password_check = form.cleaned_data['password_check']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            if password != password_check:
                form.add_error('password', "Hasła do siebie nie pasują.")
            if not form.errors:
                email = form.cleaned_data['email']
                User.objects.create_user(login, email, password,
                                         first_name=first_name,
                                         last_name=last_name)
                return HttpResponse("Udało sie założyć nowego użytkownika")
            ctx = {
                'form': form
            }
            return render(
                request,
                template_name='add_user.html',
                context=ctx
            )


class UserLoginView(View):
    def get(self, request):
        form = LoginForm()
        ctx = {
            'form': form
        }
        return render(
            request,
            template_name='login.html',
            context=ctx
        )

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('main'))
            messages.success(request, "Wrong username or password, try again or contact an administrator.")
            return redirect(reverse('login'))
        ctx = {
            'form': form
        }
        return render(
            request,
            template_name='exercises/login.html',
            context=ctx
        )


class UserLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('main'))


class TaskDetailsView(View):
    def get(self, request, task_id):
        task = Task.objects.get(id=task_id)
        ctx = {
            "task": task
        }
        return render(request, "task_details.html", ctx)


class TaskCreate(CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy('task-list')


class UpdateTask(UpdateView):

    model = Task
    # fields = "__all__"
    fields = ['status', 'end_date']
    success_url = reverse_lazy('task-list')


class DeleteTask(PermissionRequiredMixin, DeleteView):

    permission_required = 'trim_app.delete_task'
    raise_exception = True

    model = Task
    fields = "__all__"
    success_url = reverse_lazy('task-list')


class TeamMemberView(View):

    def get(self, request, teammember_id):
        team_member = TeamMember.objects.get(id=teammember_id)
        tasks_responsible = Task.objects.filter(responsible_id=teammember_id).order_by('due')
        tasks_approver = Task.objects.filter(approver_id=teammember_id).order_by('due')
        ctx = {
            "team_member": team_member,
            "tasks_responsible": tasks_responsible,
            "tasks_approver": tasks_approver,
        }
        return render(request, "team_member.html", ctx)


class AddTeamMemberView(PermissionRequiredMixin, CreateView):

    permission_required = 'trim_app.add_teammember'
    raise_exception = True

    model = TeamMember
    fields = "__all__"
    success_url = reverse_lazy('main')


class TeamView(View):

    def get(self, request, id):
        team = Team.objects.get(id=id)
        team_members = TeamMember.objects.filter(team_id=id)
        tasks = Task.objects.filter(department_id=id).order_by('due')
        ctx = {
            "team": team,
            "team_members": team_members,
            "tasks": tasks
        }
        return render(request, "team.html", ctx)


class UpdateApproval(PermissionRequiredMixin, UpdateView):

    permission_required = 'trim_app.change_task'
    raise_exception = True

    model = Task
    fields = ['approval', 'approval_date']
    success_url = reverse_lazy('task-list')


class UpdatePerson(PermissionRequiredMixin, UpdateView):

    permission_required = 'trim_app.change_task'
    raise_exception = True

    model = Task
    fields = ['responsible', 'backup', 'approver']
    success_url = reverse_lazy('task-list')

trim_app/templates/add_user.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add user">
</form>
{% endblock %}

trim_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
        <script type="text/javascript">
        function show_now() {
        var my_time = new Date();
        alert(my_time);
        }
        </script>
        <script type="text/JavaScript" src="./js/task.js"></script>
    </head>
    <body>
        <h2>Welcome to TRIM (Team Responsibilities Intelligible Manager)</h2>
        {% if messages %}
            <p class="messages">
                {% for message in messages %}
                <p class="{{ message.tags }}">{{ message }}</p>
                {% endfor %}
            </p>
        {% endif %}
        {% if request.user.is_authenticated %}
        You are logged in as: {{ request.user.first_name }} {{ request.user.last_name }}
        <p><a href="{% url 'logout' %}">Log out</a></p>
        {% else %}
        <p><a href="{% url 'login' %}">Log in</a></p>
        {% endif %}
        {% block content %}
        Welcome.
        {% endblock %}
    </body>
</html>

trim_app/templates/login.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Log in">
</form>
{% endblock %}

trim_app/templates/main.html
{% extends "base.html" %}

{% block content %}
<h4>Teams: </h4>
    {% for team in teams %}
        <ul>
            <li><a href="{% url 'team' team.id %}">{{ team.name }}: </a></li>
            {% for teammemeber in teammembers_list %}
                {% if teammemeber.team == team %}
                <a href="{% url 'team-member' teammemeber.id %}">{{ teammemeber.position }}: {{ teammemeber.name }} || </a>
                {% endif %}
            {% endfor %}
        </ul>
    {% endfor %}
<h4>Open tasks:</h4>
    <table>
        <tr>
            <th>Task</th>
            <th>Priority</th>
            <th>Frequency</th>
            <th>Month</th>
            <th>Due</th>
            <th>Department</th>
            <th>Responsible</th>
            <th>Approver</th>
            <th>Status</th>
            <th>End date</th>
        </tr>
        {% for task in task_list %}
        <tr>
            <td><a href="{% url 'task-details' task.pk %}">{{ task.name }}</a></td>
            <td>{{ task.get_priority_display }}</td>
            <td>{{ task.get_frequency_display }}</td>
            <td>{{ task.get_month_display }}</td>
            <td>{{ task.get_due_display }}</td>
            <td>{{ task.department }}</td>
            <td>{{ task.responsible }}</td>
            <td>{{ task.approver }}</td>
            <td><a href="{% url 'update-task' task.pk %}">{{ task.get_status_display }}</a></td>
            <td>{{ task.end_date }}</td>
        </tr>
        {% endfor %}
    </table>
    <p><a href="{% url 'task-list' %}">See all tasks</a></p>
    <br>
<!--<h4>Users: </h4>-->
    <!--<table>-->
        <!--<tr>-->
            <!--<th>Login</th>-->
            <!--<th>Name</th>-->
            <!--<th>Position</th>-->
            <!--<th>Team</th>-->
        <!--</tr>-->
        <!--{% for teammemeber in teammembers_list %}-->
        <!--<tr>-->
            <!--<td>{{ teammemeber.user }}</td>-->
            <!--<td><a href="{% url 'team-member' teammemeber.id %}">{{ teammemeber.name }}</a></td>-->
            <!--<td>{{ teammemeber.position }}</td>-->
            <!--<td>{{ teammemeber.team }}</td>-->
        <!--</tr>-->
        <!--{% endfor %}-->
    <!--</table>-->
{% endblock %}

trim_app/templates/task.html
{% extends "base.html" %}
{% block content %}
<form action="{% url 'add-task' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>
{% endblock %}

trim_app/templates/task_details.html
{% extends "base.html" %}
{% block content %}
<h3>Task: {{ task.name }}</h3>
<p>Description: {{ task.description }}</p>
<p>Priority: {{ task.get_priority_display }}</p>
<p>Frequency: {{ task.get_frequency_display }}</p>
<p>Start date: {{ task.start_date }}</p>
<p>Month: {{ task.get_month_display }}</p>
<p>Due: {{ task.get_due_display }}</p>
<p>Department: {{ task.department }}</p>
<p>Responsible: {{ task.responsible }} <a href="{% url 'update-person' task.pk %}"> update </a></p>
<p>Backup: {{ task.backup }} <a href="{% url 'update-person' task.pk %}"> update </a></p>
<p>Approver: {{ task.approver }}<a href="{% url 'update-person' task.pk %}"> update </a></p></p>
<p>Status: {{ task.get_status_display }}<a href="{% url 'update-task' task.pk %}"> update </a></p>
<p>End date: {{ task.end_date }}</p>
<p>Approval: {{ task.approval }}<a href="{% url 'update-approval' task.pk %}"> approve </a></p>
<p>Approval date: {{ task.approval_date }}</p>
<p><a href="{% url 'delete-task' task.pk %}">delete task</a></p>
<p><a href="{% url 'task-list' %}">Back to task list</a></p>
{% endblock %}

trim_app/templates/task_list.html
{% extends "base.html" %}

{% block content %}
<h3>Task list: </h3>
    <table>
        <tr>
            <th>Task</th>
            <th>Priority</th>
            <th>Frequency</th>
            <th>Month</th>
            <th>Due</th>
            <th>Department</th>
            <th>Responsible</th>
            <th>Approver</th>
            <th>Status</th>
            <th>End date</th>
            <th>Approval</th>
            <th>Approval date</th>
            <th></th>
        </tr>
        {% for task in task_list %}
        <tr>
            <td><a href="{% url 'task-details' task.pk %}">{{ task.name }}</a></td>
            <td>{{ task.get_priority_display }}</td>
            <td>{{ task.get_frequency_display }}</td>
            <td>{{ task.get_month_display }}</td>
            <td>{{ task.get_due_display }}</td>
            <td><a href="/team/{{ task.department_id }}/">{{ task.department }}</a></td>
            <td><a href="/team_member/{{ task.responsible_id }}/">{{ task.responsible }}</a></td>
            <td><a href="/team_member/{{ task.approver_id }}/">{{ task.approver }}</a></td>
            <td><a href="{% url 'update-task' task.pk %}">{{ task.get_status_display }}</a></td>
            <td>{{ task.end_date }}</td>
            <td><a href="{% url 'update-approval' task.pk %}">{{ task.approval }}</a></td>
            <td>{{ task.approval_date }}</td>
            <td><a href="{% url 'delete-task' task.pk %}">delete task</a></td>
        </tr>
        {% endfor %}
    </table>
    <p><a href="{% url 'create-task' %}">Add task</a></p>
<p><a href="{% url 'main' %}">Back to main page</a></p>
{% endblock %}

trim_app/templates/team.html
{% extends "base.html" %}

{% block content %}
<h3>Team: {{ team.name }}</h3>
<h4>Team members: </h4>
    <ul>
        {% for teammember in team_members %}
        <li><a href="/team_member/{{ teammember.id }}/">{{ teammember.name }}</a> - {{ teammember.position }}</li>
    {% endfor %}
    </ul>
<p><a href="{% url 'add-team-member' %}">Add team member</a></p>
<h4>Tasks: </h4>
<table>
    <tr>
        <th>Task</th>
        <th>Priority</th>
        <th>Frequency</th>
        <th>Month</th>
        <th>Due</th>
        <th>Department</th>
        <th>Responsible</th>
        <th>Approver</th>
        <th>Status</th>
        <th>End date</th>
        <th>Approval</th>
        <th>Approval date</th>
    </tr>
    {% for task in tasks %}
    <tr>
        <td><a href="{% url 'task-details' task.pk %}">{{ task.name }}</a></td>
        <td>{{ task.get_priority_display }}</td>
        <td>{{ task.get_frequency_display }}</td>
        <td>{{ task.get_month_display }}</td>
        <td>{{ task.get_due_display }}</td>
        <td>{{ task.department }}</td>
        <td>{{ task.responsible }}</td>
        <td>{{ task.approver }}</td>
        <td><a href="{% url 'update-task' task.pk %}">{{ task.get_status_display }}</a></td>
        <td>{{ task.end_date }}</td>
        <td><a href="{% url 'update-approval' task.pk %}">{{ task.approval }}</a></td>
        <td>{{ task.approval_date }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{% url 'create-task' %}">Add task</a></p>
<p><a href="{% url 'task-list' %}">See all tasks</a></p>
<p><a href="{% url 'main' %}">Back to main page</a></p>
{% endblock %}
</html>

trim_app/templates/team_member.html
{% extends "base.html" %}

{% block content %}
<h3>{{ team_member.name }}</h3>
<p>Team: <a href="/team/{{ team_member.team_id }}/">{{ team_member.team }}</a></p>
<p>Position: {{ team_member.position }}</p>
<h4>Tasks to do:</h4>
<table>
    <tr>
        <th>Task</th>
        <th>Priority</th>
        <th>Frequency</th>
        <th>Month</th>
        <th>Due</th>
        <th>Department</th>
        <th>Responsible</th>
        <th>Approver</th>
        <th>Status</th>
        <th>End date</th>
        <th>Approval</th>
        <th>Approval date</th>
    </tr>
    {% for task in tasks_responsible %}
    <tr>
        <td><a href="{% url 'task-details' task.pk %}">{{ task.name }}</a></td>
        <td>{{ task.get_priority_display }}</td>
        <td>{{ task.get_frequency_display }}</td>
        <td>{{ task.get_month_display }}</td>
        <td>{{ task.get_due_display }}</td>
        <td>{{ task.department }}</td>
        <td>{{ task.responsible }}</td>
        <td>{{ task.approver }}</td>
        <td><a href="{% url 'update-task' task.pk %}">{{ task.get_status_display }}</a></td>
        <td>{{ task.end_date }}</td>
        <td>{{ task.approval }}</td>
        <td>{{ task.approval_date }}</td>
    </tr>
    {% endfor %}
</table>
<br>
<h4>Tasks to approve:</h4>
<table>
    <tr>
        <th>Task</th>
        <th>Priority</th>
        <th>Frequency</th>
        <th>Month</th>
        <th>Due</th>
        <th>Department</th>
        <th>Responsible</th>
        <th>Approver</th>
        <th>Status</th>
        <th>End date</th>
        <th>Approval</th>
        <th>Approval date</th>
        <th></th>
    </tr>
    {% for task in tasks_approver %}
    <tr>
        <td><a href="{% url 'task-details' task.pk %}">{{ task.name }}</a></td>
        <td>{{ task.get_priority_display }}</td>
        <td>{{ task.get_frequency_display }}</td>
        <td>{{ task.get_month_display }}</td>
        <td>{{ task.get_due_display }}</td>
        <td>{{ task.department }}</td>
        <td>{{ task.responsible }}</td>
        <td>{{ task.approver }}</td>
        <td>{{ task.get_status_display }}</td>
        <td>{{ task.end_date }}</td>
        <td><a href="{% url 'update-approval' task.pk %}">{{ task.approval }}</a></td>
        <td>{{ task.approval_date }}</td>
        <td><a href="{% url 'delete-task' task.pk %}">delete task</a></td>
    </tr>
    {% endfor %}
</table>
<p><a href="{% url 'create-task' %}">Add task</a></p>
<p><a href="{% url 'task-list' %}">See all tasks</a></p>
<p><a href="{% url 'main' %}">Back to main page</a></p>
{% endblock %}